config/routes.rb
Timetable::Application.routes.draw do
  get "teacher/index"

  root :to => 'login#index'
  
  match "/login" => "login#index", :as => "login"
  match "/login/verify" => "login#verify", :as => "login_verify", :via => :post
  match "/logout" => "login#destroy", :as => "logout"
   
  
  match "/register" => "register#show", :as => "register"
  match "/register/verify" => "register#verify", :as => "register_verify", :via => :post

  match "/admin" => "admin#index", :as => "admin"
  match "/admin/new_teacher" => "teacher#new_teacher", :as => "admin_new_teacher"
  match "/admin/save_teacher" => "teacher#save_teacher", :as => "admin_save_teacher", :via => :post
  match "/admin/edit_teacher/show" => "teacher#edit_teacher", :as => "admin_show_edit_teacher"
  match "/admin/edit_teacher/:id" => "teacher#edit_teacher", :as => "admin_edit_teacher"
  match "/admin/delete_teacher/:id" => "teacher#delete_teacher", :as => "admin_delete_teacher"
  
  match "/admin/edit_timesheet" => "timesheets#edit", :as => "admin_edit_timesheet"
  match "/admin/save_timesheet" => "timesheets#save", :as => "admin_save_timesheet"
  match "/admin/timesheet" => "timesheets#index", :as => "admin_timesheet"
  
  match "/teacher" => "teacher#index", :as => "teacher"
  match "/teacher/timesheet/:id" => "timesheets#index", :as => "teacher_timesheet"
  
  resources :users, :courses, :course_types, :hours, :teaches, :roles, :wishes, :timesheets

end

app/models/bjlogin.rb
class Bjlogin < ActiveRecord::Base
end

app/models/common.rb
class Common < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teaches, :dependent => :destroy
  has_many :users, :through => :teaches
end 

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :hours
  has_many :teaches, :through => :hours
end
 

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :teach
  belongs_to :course_type
  belongs_to :timesheet
end
 

app/models/personal.rb
class Personal < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/qinmiset.rb
class Qinmiset < ActiveRecord::Base
end

app/models/regist1.rb
class Regist1 < ActiveRecord::Base
end

app/models/register.rb
class Register < ActiveRecord::Base
    validates :name, :password,:presence => true
end 

app/models/role.rb
class Role < ActiveRecord::Base
  def admin?
    self.permission == "admin"
  end
end
 

app/models/shouye.rb
class Shouye < ActiveRecord::Base
end

app/models/teach.rb
class Teach < ActiveRecord::Base
  belongs_to :user
  belongs_to :course, :dependent => :destroy
  has_many :hours, :dependent => :destroy
  has_many :wishes, :dependent => :destroy
end
 

app/models/teamset.rb
class Teamset < ActiveRecord::Base
end

app/models/timeset.rb
class Timeset < ActiveRecord::Base
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :hour
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # one-to-many association, the foreign key pointing to the Role table row is kept in this table
  # read for details: 
  # http://guides.rubyonrails.org/association_basics.html 
  # http://duanesbrain.blogspot.com/2006/05/ruby-on-rails-hasone-versus-belongsto.html
  belongs_to :role
  
  has_many :teaches, :dependent => :destroy
  has_many :courses, :through => :teaches
end 

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :teaches
  belongs_to :hour
end
 

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_filter :authenticate_for_admin
  
  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wishes }
    end
  end

  # GET /wishes/1 
  # GET /wishes/1.json
  def show
    @wish = Wish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wish }
    end
  end

  # GET /wishes/new
  # GET /wishes/new.json
  def new
    @wish = Wish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wish }
    end
  end

  # GET /wishes/1/edit
  def edit
    @wish = Wish.find(params[:id])
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(params[:wish])

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render json: @wish, status: :created, location: @wish }
      else
        format.html { render action: "new" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wishes/1
  # PUT /wishes/1.json
  def update
    @wish = Wish.find(params[:id])

    respond_to do |format|
      if @wish.update_attributes(params[:wish])
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy

    respond_to do |format|
      format.html { redirect_to wishes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end 

app/helpers/hours_helper.rb
module HoursHelper
end
 

app/helpers/login_helper.rb
module LoginHelper
end
 

app/helpers/wishes_helper.rb
module WishesHelper
end
 

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to_be_held %><br />
    <%= f.check_box :to_be_held %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
    <%= f.datetime_select :when %>
  </div>
  <div class="field">
    <%= f.label :important %><br />
    <%= f.check_box :important %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>
 

app/views/wishes/index.html.erb
<h1>Listing wishes</h1>

<table>
  <tr>
    <th>To be held</th>
    <th>When</th>
    <th>Important</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wishes.each do |wish| %>
  <tr>
    <td><%= wish.to_be_held %></td>
    <td><%= wish.when %></td>
    <td><%= wish.important %></td>
    <td><%= link_to 'Show', wish %></td>
    <td><%= link_to 'Edit', edit_wish_path(wish) %></td>
    <td><%= link_to 'Destroy', wish, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
 
<br />

<%= link_to 'New Wish', new_wish_path %>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>
 

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>To be held:</b>
  <%= @wish.to_be_held %>
</p>

<p>
  <b>When:</b>
  <%= @wish.when %>
</p>

<p>
  <b>Important:</b>
  <%= @wish.important %>
</p>


<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>
 