config/routes.rb
Timetable::Application.routes.draw do
  get "teacher/index"

  root :to => 'login#index'
  
  match "/login" => "login#index", :as => "login"
  match "/login/verify" => "login#verify", :as => "login_verify", :via => :post
  match "/logout" => "login#destroy", :as => "logout"
   
  
  match "/register" => "register#show", :as => "register"
  match "/register/verify" => "register#verify", :as => "register_verify", :via => :post

  match "/admin" => "admin#index", :as => "admin"
  match "/admin/new_teacher" => "teacher#new_teacher", :as => "admin_new_teacher"
  match "/admin/save_teacher" => "teacher#save_teacher", :as => "admin_save_teacher", :via => :post
  match "/admin/edit_teacher/show" => "teacher#edit_teacher", :as => "admin_show_edit_teacher"
  match "/admin/edit_teacher/:id" => "teacher#edit_teacher", :as => "admin_edit_teacher"
  match "/admin/delete_teacher/:id" => "teacher#delete_teacher", :as => "admin_delete_teacher"
  
  match "/admin/edit_timesheet" => "timesheets#edit", :as => "admin_edit_timesheet"
  match "/admin/save_timesheet" => "timesheets#save", :as => "admin_save_timesheet"
  match "/admin/timesheet" => "timesheets#index", :as => "admin_timesheet"
  
  match "/teacher" => "teacher#index", :as => "teacher"
  match "/teacher/timesheet/:id" => "timesheets#index", :as => "teacher_timesheet"
  
  resources :users, :courses, :course_types, :hours, :teaches, :roles, :wishes, :timesheets

end

app/models/bjlogin.rb
class Bjlogin < ActiveRecord::Base
end

app/models/common.rb
class Common < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teaches, :dependent => :destroy
  has_many :users, :through => :teaches
end 

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :hours
  has_many :teaches, :through => :hours
end
 

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :teach
  belongs_to :course_type
  belongs_to :timesheet
end
 

app/models/personal.rb
class Personal < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/qinmiset.rb
class Qinmiset < ActiveRecord::Base
end

app/models/regist1.rb
class Regist1 < ActiveRecord::Base
end

app/models/register.rb
class Register < ActiveRecord::Base
    validates :name, :password,:presence => true
end 

app/models/role.rb
class Role < ActiveRecord::Base
  def admin?
    self.permission == "admin"
  end
end
 

app/models/shouye.rb
class Shouye < ActiveRecord::Base
end

app/models/teach.rb
class Teach < ActiveRecord::Base
  belongs_to :user
  belongs_to :course, :dependent => :destroy
  has_many :hours, :dependent => :destroy
  has_many :wishes, :dependent => :destroy
end
 

app/models/teamset.rb
class Teamset < ActiveRecord::Base
end

app/models/timeset.rb
class Timeset < ActiveRecord::Base
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :hour
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # one-to-many association, the foreign key pointing to the Role table row is kept in this table
  # read for details: 
  # http://guides.rubyonrails.org/association_basics.html 
  # http://duanesbrain.blogspot.com/2006/05/ruby-on-rails-hasone-versus-belongsto.html
  belongs_to :role
  
  has_many :teaches, :dependent => :destroy
  has_many :courses, :through => :teaches
end 

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :teaches
  belongs_to :hour
end
 

app/helpers/admin_helper.rb
module AdminHelper
end 

app/helpers/hours_helper.rb
module HoursHelper
end
 

app/views/admin/index.html.erb
<h1 style="text-align: center;"><%= t(:admin)%></h1> 

app/views/shared/_header.html.erb
<table id="userBar">
<tr>
	<% if user_name.nil? %>
		<td style="text-align: right;"></td>
       	<td style="text-align: right; width: 120px;"><a href="<%= login_path %>"><%= t(:login) %></a></td>
		<td style="text-align: right; width: 120px;"><a href="../register">register</a></td>
    <% else 
    	if admin %>
		<td style="text-align: right;"><%= t(:welcome) %>, <b><%= user_name %></b> &nbsp;&nbsp;&nbsp;&nbsp;</td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_timesheet_path %>"><%= t(:timetable) %></a></td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_edit_timesheet_path %>"><%= t(:edit_timetable) %></a></td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_new_teacher_path %>"><%= t(:new_teacher) %></a></td>
		<td style="text-align: center; width: 120px;"><a href="<%= admin_show_edit_teacher_path %>"><%= t(:edit_teacher) %></a></td>
        <td style="text-align: center; width: 100px;"><a href="<%= logout_path %>"><%= t(:logout) %></a></td>	
    <% 	else %>
    	<td style="text-align: right;"><%= t(:welcome) %>, <b><%= user_name %></b> &nbsp;&nbsp;&nbsp;&nbsp;</td>
    	<td style="text-align: center; width: 120px;"><a href="<%= teacher_timesheet_path(user_id) %>"><%= t(:timetable) %></a></td>
    	<!-- <td style="text-align: center; width: 120px;"><a href="<%= "/teacher" %>"><%= t(:edit_wishes) %></a></td> -->
        <td style="text-align: center; width: 100px;"><a href="<%= logout_path %>"><%= t(:logout) %></a></td>	
   	<% 	end
   	 end %>
   	 <td style="text-align: right; width: 25px;">

	</td>
	<td style="text-align: right; width: 25px;">
    
</tr>
</table> 